[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "art4r"
version = "0.8"
description = "Streamlit application - NCU RT4 6.7 GHz automated data reduction tool"
readme = "README.md"
requires-python = ">=3.11, <3.13"
dependencies = [
    "streamlit>=1.30.0",
    "tensorflow",
    "numpy",
    "platformdirs",
    "validators",
    "scikit-learn",
    "requests",
    "ncu-salsa-rt4 @ git+https://github.com/dachshund-ncu/ncu-salsa-rt4.git",
]

[project.scripts]
art4r = "services.main:cli"

[tool.hatch.build.targets.wheel]
packages = ["services", "data"]

[tool.hatch.metadata]
allow-direct-references=true